name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build


    # Docker 로그인
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-blog:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/react-blog:${{ github.sha }}


    # EC2 서버에 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          CONTAINER_ID=$(docker ps -q -f name=react-blog)
          if [ ! -z "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi

          docker pull ${{ secrets.DOCKER_USERNAME }}/react-blog:${{ github.sha }}
          docker run -d --name react-blog --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/react-blog:${{ github.sha }}
          docker image prune -f

